### ISSUE TITLE
Add Compy endpoint to Globus file

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#274]
Add Compy endpoint to Globus file.

In https://github.com/E3SM-Project/zstash/blob/main/zstash/globus.py, add Compy's Globus endpoint.

**Comment by forsyth2** [comment]
@mahf708 Did you (or can you) run the following on Compy?

```
$ cd zstash
# <Activate a conda dev environment>
$ pip install .
$ python -m unittest tests/test_globus.py
```

I'm getting the following error on both `main` and this branch.
```
======================================================================
ERROR: testLs (tests.test_globus.TestGlobus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 183, in testLs
    self.helperLsGlobus(
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 161, in helperLsGlobus
    self.preactivate_globus()
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 62, in preactivate_globus
    native_client.login(no_local_server=True, refresh_tokens=True)
  File "/qfs/people/fors729/mambaforge/envs/zstash_dev/lib/python3.9/site-packages/fair_research_login/client.py", line 157, in login
    auth_code = self.get_code(requested_scopes, refresh_tokens,
  File "/qfs/people/fors729/mambaforge/envs/zstash_dev/lib/python3.9/site-packages/fair_research_login/client.py", line 197, in get_code
    auth_url = self.client.oauth2_get_authorize_url(
TypeError: oauth2_get_authorize_url() got an unexpected keyword argument 'additional_params'
```
That error message isn't terribly helpful. (It looks like my Globus endpoint is activated: https://app.globus.org/file-manager/collections/68fbd2fa-83d7-11e9-8e63-029d279f7e24/overview)

Perhaps related, using the latest Unified RC, I get:
```
$ source /share/apps/E3SM/conda_envs/test_e3sm_unified_1.9.0rc6_compy.sh
$ python -m unittest tests/test_globus.py
Removing test files, both locally and at the HPSS repo
E
======================================================================
ERROR: testLs (tests.test_globus.TestGlobus)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 183, in testLs
    self.helperLsGlobus(
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 161, in helperLsGlobus
    self.preactivate_globus()
  File "/qfs/people/fors729/zstash/tests/test_globus.py", line 69, in preactivate_globus
    r = self.transfer_client.endpoint_autoactivate(ep_id, if_expires_in=600)
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/services/transfer/client.py", line 458, in endpoint_autoactivate
    return self.post(
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/client.py", line 157, in post
    return self.request(
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/client.py", line 294, in request
    r = self.transport.request(
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/transport/requests.py", line 320, in request
    self._set_authz_header(authorizer, req)
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/transport/requests.py", line 252, in _set_authz_header
    authz_header = authorizer.get_authorization_header()
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/authorizers/renewing.py", line 171, in get_authorization_header
    self.ensure_valid_token()
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/authorizers/renewing.py", line 165, in ensure_valid_token
    self._get_new_access_token()
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/authorizers/renewing.py", line 125, in _get_new_access_token
    res = self._get_token_response()
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/authorizers/refresh_token.py", line 80, in _get_token_response
    return self.auth_client.oauth2_refresh_token(self.refresh_token)
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/services/auth/client/native_client.py", line 130, in oauth2_refresh_token
    return self.oauth2_token(form_data, body_params=body_params)
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/services/auth/client/base.py", line 474, in oauth2_token
    self.post(
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/client.py", line 157, in post
    return self.request(
  File "/share/apps/E3SM/conda_envs/base/envs/e3sm_unified_1.9.0rc6_login/lib/python3.10/site-packages/globus_sdk/client.py", line 312, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', None, 400, 'Error', 'Bad Request')
```

**Comment by forsyth2** [comment]
Ah, I knew I had seen this error before. Searching GitHub, I found `additional_params` occurs in https://github.com/E3SM-Project/zstash/pull/201#issuecomment-1071801611 and https://github.com/E3SM-Project/zstash/pull/250#issuecomment-1412932989. 

In https://github.com/E3SM-Project/zstash/pull/250#issuecomment-1413030242, Xylar says: 
>  it seems like the version of fair-research-login` is most likely to be responsible

```
$ git grep -n fair
conda/dev.yml:12:  - fair-research-login=0.2.0
conda/meta.yaml:24:    - fair-research-login >=0.2.6,<0.3.0
tests/test_globus.py:8:from fair_research_login.client import NativeClient
zstash/globus.py:9:from fair_research_login.client import NativeClient
```

Changing `fair-research-login=0.2.0` to `0.2.6` just seems to make the test hang however. 

@mahf708 If you can run the test on Compy and see if you run into the same issue, that would be helpful in my debugging. Thanks!

**Comment by forsyth2** [comment]
> Sorry, I let you down on this. I am on it right now.

No worries, thanks!

> I cannot reproduce your errors, but I get the above...

> can you please check your https://app.globus.org/activity to see if the file transfers are hanging there?

I get the same errors as in your image. Clicking "view details", I get:
```
{
  "context": [
    {
      "operation": "Directory List / File Scan",
      "path": "/qfs/people/fors729/zstash/zstash_test/zstash/000000.tar"
    }
  ],
  "error": {
    "body": "550-GlobusError: v=1 c=PATH_NOT_FOUND%0D%0A550-GridFTP-Errno: 2%0D%0A550-GridFTP-Reason: System error in stat%0D%0A550-GridFTP-Error-String: No such file or directory%0D%0A550 End.%0D%0A",
    "code": 550,
    "endpoint": "pic#compy-dtn (68fbd2fa-83d7-11e9-8e63-029d279f7e24)",
    "server": "gsiftp://compy-dtn.pnl.gov:2811",
    "type": "FTPServerError"
  }
}
```
I wasn't aware of the extra detail there; that matches what you got.

> is this an error you've seen before? Where some files are missing?

I don't think so? At least, it wasn't a big enough problem to remember. And almost certainly not on this small test case.

**Comment by forsyth2** [comment]
@mahf708 Thank you for pointing out the diff from the latest release version. I just ran on the latest official release of Unified, and the Globus test actually gives the same result.

That seems to indicate something happened with the way Globus, `fair-research-login`, or perhaps another  third-party package work internally.

**Comment by forsyth2** [comment]
Actually, anything involving a package wouldn't make sense, because we have the version pinned. That means it must be something that changed with Globus, right?

**Comment by forsyth2** [comment]
But these are still packages. We know `zstash` worked on the last release. And now that _same exact_ code (and dependencies!) does not work.

**Comment by forsyth2** [comment]
The Globus test on Compy is the only issue I'm having with the upcoming `zstash` release. This test appears to fail consistently regardless of what commit or dev environment is being used.

**Comment by forsyth2** [comment]
(I suppose now I should have made these comments in a separate issue, but I thought this endpoint change might be the necessary fix. Apparently that's not the case).

**Comment by forsyth2** [comment]
@mahf708 Thanks you for helping debug. I'm going to open an issue specifically to address this, since it's now clearly unrelated to this pull request.

**Comment by forsyth2** [comment]
I created #279. Unfortunately, I can't test this pull request on Compy until that is resolved.
