### ISSUE TITLE
Various error cases on `zstash extract` and `zstash ls`

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zstash#313]
### Request criteria

- [X] I searched the [zstash GitHub Discussions](https://github.com/E3SM-Project/zstash/discussions) to find a similar question and didn't find it.
- [X] I searched the [zstash documentation](https://e3sm-project.github.io/zstash).
- [X] This issue does not match the other templates (i.e., it is not a bug report, documentation request, feature request, or a question.)

### Issue description

Several errors appear to happen on `zstash extract` and `zstash ls`. The following runs are from Perlmutter.

Case 1: New Unified, `zstash ls` on whole directory
=====
```
$ mkdir 20231114_case1
$ cd 20231114_case1
$ source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.9.1rc1_pm-cpu.sh
$ zstash ls --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101
For help, please see https://e3sm-project.github.io/zstash. Ask questions at https://github.com/E3SM-Project/zstash/discussions/categories/q-a.
INFO: Transferring file from HPSS: zstash/index.db
ERROR: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 105, in ls_database
    hpss_get(hpss, get_db_filename(cache), cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 118, in hpss_get
    hpss_transfer(hpss, file_path, "get", cache, False)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 95, in hpss_transfer
    run_command(command, error_str)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/utils.py", line 66, in run_command
    raise RuntimeError(error_str)
RuntimeError: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/bin/zstash", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/main.py", line 74, in main
    ls()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 34, in ls
    matches: List[FilesRow] = ls_database(args, cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 107, in ls_database
    raise FileNotFoundError("There was nothing to ls.")
FileNotFoundError: There was nothing to ls.
```
Notably:
```
RuntimeError: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
```
and
```
FileNotFoundError: There was nothing to ls.
```
Interestingly, the first time I ran this command (from a different directory), I actually did get results printed, with no error messages.

Case 2: New Unified, `zstash extract` on subset of directory
=====
```
$ mkdir 20231114_case2
$ cd 20231114_case2
$ source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.9.1rc1_pm-cpu.sh
$ zstash extract --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101 "archive/rest/1855-01-01-00000/*"
For help, please see https://e3sm-project.github.io/zstash. Ask questions at https://github.com/E3SM-Project/zstash/discussions/categories/q-a.
INFO: Transferring file from HPSS: zstash/index.db
ERROR: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/bin/zstash", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/main.py", line 68, in main
    extract()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/extract.py", line 45, in extract
    failures: List[FilesRow] = extract_database(args, cache, keep_files)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/extract.py", line 173, in extract_database
    hpss_get(hpss, get_db_filename(cache), cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 118, in hpss_get
    hpss_transfer(hpss, file_path, "get", cache, False)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 95, in hpss_transfer
    run_command(command, error_str)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/utils.py", line 66, in run_command
    raise RuntimeError(error_str)
RuntimeError: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
```

Case 3: New Unified, `zstash ls` on subset of directory
=====
```
$ mkdir 20231114_case3
$ cd 20231114_case3
$ source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.9.1rc1_pm-cpu.sh
$ zstash ls --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101 "archive/rest/1855-01-01-00000/*"
```

Same errors as case 1:
```
For help, please see https://e3sm-project.github.io/zstash. Ask questions at https://github.com/E3SM-Project/zstash/discussions/categories/q-a.
INFO: Transferring file from HPSS: zstash/index.db
ERROR: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 105, in ls_database
    hpss_get(hpss, get_db_filename(cache), cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 118, in hpss_get
    hpss_transfer(hpss, file_path, "get", cache, False)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 95, in hpss_transfer
    run_command(command, error_str)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/utils.py", line 66, in run_command
    raise RuntimeError(error_str)
RuntimeError: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/bin/zstash", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/main.py", line 74, in main
    ls()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 34, in ls
    matches: List[FilesRow] = ls_database(args, cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 107, in ls_database
    raise FileNotFoundError("There was nothing to ls.")
FileNotFoundError: There was nothing to ls.
```

Case 4: New Unified, `zstash extract` on whole directory; followed by `zstash ls` on subset of directory
=====
```
$ mkdir 20231114_case4
$ cd 20231114_case4
$ source /global/common/software/e3sm/anaconda_envs/test_e3sm_unified_1.9.1rc1_pm-cpu.sh
$ zstash extract --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101 
```
Same errors as case 2:
```
For help, please see https://e3sm-project.github.io/zstash. Ask questions at https://github.com/E3SM-Project/zstash/discussions/categories/q-a.
INFO: Transferring file from HPSS: zstash/index.db
ERROR: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/bin/zstash", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/main.py", line 68, in main
    extract()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/extract.py", line 45, in extract
    failures: List[FilesRow] = extract_database(args, cache, keep_files)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/extract.py", line 173, in extract_database
    hpss_get(hpss, get_db_filename(cache), cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 118, in hpss_get
    hpss_transfer(hpss, file_path, "get", cache, False)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/hpss.py", line 95, in hpss_transfer
    run_command(command, error_str)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/utils.py", line 66, in run_command
    raise RuntimeError(error_str)
RuntimeError: Error=Transferring file from HPSS: index.db, Command was `hsi -q "cd /home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101; get index.db"`. This command includes `hsi`. Be sure that you have logged into `hsi`. This command includes `cd`. Check that this directory exists and contains the needed files
```

I then ran `zstash ls`:
```
$ zstash ls --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101 "archive/rest/1855-01-01-00000/*"
For help, please see https://e3sm-project.github.io/zstash. Ask questions at https://github.com/E3SM-Project/zstash/discussions/categories/q-a.
Traceback (most recent call last):
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/bin/zstash", line 10, in <module>
    sys.exit(main())
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/main.py", line 74, in main
    ls()
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 34, in ls
    matches: List[FilesRow] = ls_database(args, cache)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/ls.py", line 120, in ls_database
    update_config(cur)
  File "/global/common/software/e3sm/anaconda_envs/base/envs/e3sm_unified_1.9.1rc1_login/lib/python3.10/site-packages/zstash/utils.py", line 117, in update_config
    cur.execute("select value from config where arg=?", (attr,))
sqlite3.OperationalError: no such table: config
```

Thoughts
=======
- https://www.nersc.gov/live-status/motd/ shows HPSS as up
- I can log into `hsi` on Perlmutter, so I definitely have access to `hsi` set up.
- Why did I get a different result re-trying case 1?
- When Jill (@chengzhuzhang) ran `zstash ls --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101` (i.e., case 1), she just got the `sqlite3.OperationalError: no such table: config` error found in the last part of case 4. That means case 1 has produced 3 different results (1 success and 1 failure for me, 1 different failure for Jill).
- When Jill ran `zstash extract --hpss=/home/projects/e3sm/www/WaterCycle/E3SMv2/LR/v2.LR.historical_0101 "archive/rest/1855-01-01-00000/*"` (i.e. case 2), it worked. That means case 2 has produced 2 different results (1 failure for me, 1 success for Jill).
- Jill suggested that perhaps a single file on HPSS cannot be accessed by two people at the same time. However, I just ran the 4 cases above while Jill was not running anything and still got errors.

**Comment by forsyth2** [comment]
@xylar FYI... we're not really sure what's going on here. It doesn't seem like it was introduced in this version of Unified though. We encountered similar errors on the latest released version of Unified.

**Comment by forsyth2** [comment]
@chengzhuzhang I just ran 
```
git checkout main
error: unable to write file .github/DISCUSSION_TEMPLATE/questions.yml
fatal: sha1 file '/global/homes/f/forsyth/zstash/.git/index.lock' write error: Disk quota exceeded
```
So I have a feeling these errors are caused by disk quota limits.

**Comment by forsyth2** [comment]
Yes, that must be it. When I ran Case 2 the first time, I hit 31G. It didn't click for me when you mentioned the home directory that that has a lower quota.

**Comment by chengzhuzhang** [comment]
Yes,  I had error when running zstash in my home directory, but no errors when I switch to use `/global/cfs/cdirs/e3sm/`. My home directory also hit 30+ G.

**Comment by chengzhuzhang** [comment]
Thanks for adding this issue. The error message was not very helpful to trouble shooting "Disk quota exceeded` problem`. Having the issue documented helps.

**Comment by forsyth2** [comment]
From `/pscratch/sd/f/forsyth/zstash_testing`: 

Case 1: success
Case 2: success
Case 3: success
Case 4: appears to be successful (stopped since this command would take a while to run)

Ok, yes it looks like this was just the disk quota issue then, thankfully.

> The error message was not very helpful

I created #314 in the Discussions Q&A for when someone else inevitably runs into this again. Perhaps that error message line itself should add "check if you've reached disk quota" as yet another possibility.
